spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  social:
    google:
      url:
        profile: https://www.googleapis.com/oauth2/v3/userinfo
    kakao:
      url:
        profile: https://kapi.kakao.com/v2/user/me
    apple:
      url:
        keys: https://appleid.apple.com/auth/keys
jwt:
  secret: ${JWT_SECRET}

  access:
    expiration: 3600000 # 1??
    header: X-AUTH-TOKEN

  refresh:
    expiration: 1209600000 # 2?
    header: rememberedToken

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
      credentials:
        access-key: ${S3_ACCESS}
        secret-key: ${S3_SECRET}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
